# Generated by Django 3.2.9 on 2022-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_сalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(max_length=150, verbose_name='Статус события')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
