# Generated by Django 3.2.9 on 2022-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_сalendar', '0003_auto_20220414_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
    ]
