# Generated by Django 3.2.9 on 2022-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_сalendar', '0004_auto_20220418_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Активен', 'Активен'), ('Закончен', 'Закончен')], default='В ожидании', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
