# Generated by Django 3.2.9 on 2022-06-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSelectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос с несколькими правильными вариантами ответов',
                'verbose_name_plural': 'Вопросы с несколькими правильными вариантами ответов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('comment', models.TextField(verbose_name='Комментарие к вопросу')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вопрос с одним правильным вариантом ответа',
                'verbose_name_plural': 'Вопросы с одним правильным вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='OneRightAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_right_answer', models.BooleanField(verbose_name='Правильный ответ')),
                ('comment', models.TextField(verbose_name='Комментарие к ответу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианты ответов',
                'verbose_name_plural': 'Варианты ответов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiSelectRightAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_right_answer', models.BooleanField(verbose_name='Правильный ответ')),
                ('comment', models.TextField(verbose_name='Комментарие к ответу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.multiselectquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианты ответов',
                'verbose_name_plural': 'Варианты ответов',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multiselectquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Задание'),
        ),
    ]
