# Generated by Django 3.2.9 on 2022-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Информация о себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_page_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
