# Generated by Django 3.2.9 on 2022-03-10 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sort', models.PositiveIntegerField(verbose_name='Сортировка')),
                ('short_description', models.CharField(blank=True, max_length=175, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_lesson/courses/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('view', 'View'), ('ready', 'Ready')], default='draft', max_length=15, verbose_name='Статус')),
                ('is_certificated', models.BooleanField(verbose_name='Полсе прохождения курса выдается сертификат?')),
                ('certificate_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст на сертификате')),
                ('certic_preview_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('users_ended', models.ManyToManyField(blank=True, related_name='courses_ended', to=settings.AUTH_USER_MODEL)),
                ('users_likes', models.ManyToManyField(blank=True, related_name='courses_liked', to=settings.AUTH_USER_MODEL)),
                ('users_started', models.ManyToManyField(blank=True, related_name='courses_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('sort', models.PositiveIntegerField(verbose_name='Сортировка')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
                ('users_ended', models.ManyToManyField(blank=True, related_name='modules_ended', to=settings.AUTH_USER_MODEL)),
                ('users_started', models.ManyToManyField(blank=True, related_name='modules_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модули',
                'verbose_name_plural': 'Модули',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='MultiSelectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос с несколькими правильными вариантами ответов',
                'verbose_name_plural': 'Вопросы с несколькими правильными вариантами ответов',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_url', models.URLField(verbose_name='Ccылка на видео (если есть видео)')),
                ('type', models.CharField(choices=[('Автоматическая проверка', 'Автоматическая проверка'), ('Ручная проверка', 'Ручная проверка')], default='Автоматическая проверка', max_length=23, verbose_name='Тип задания')),
                ('sort', models.PositiveIntegerField(verbose_name='Сортировка')),
                ('is_last_task', models.BooleanField(verbose_name='Это итоговое задание в этом модуле')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Модуль')),
                ('users_started', models.ManyToManyField(blank=True, related_name='lessons_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('comment', models.TextField(verbose_name='Комментарие к вопросу')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вопрос с одним правильным вариантом ответа',
                'verbose_name_plural': 'Вопросы с одним правильным вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='OneRightAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_right_answer', models.BooleanField(verbose_name='Правильный ответ')),
                ('comment', models.TextField(verbose_name='Комментарие к ответу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианты ответов',
                'verbose_name_plural': 'Варианты ответов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiSelectRightAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_right_answer', models.BooleanField(verbose_name='Правильный ответ')),
                ('comment', models.TextField(verbose_name='Комментарие к ответу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.multiselectquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианты ответов',
                'verbose_name_plural': 'Варианты ответов',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multiselectquestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание'),
        ),
    ]
