# Generated by Django 3.2.9 on 2022-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220310_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_ended',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_started',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
