# Generated by Django 3.2.9 on 2022-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220310_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evaluation_criterion',
            field=models.TextField(default='', verbose_name='Критерия оценки'),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Максимальное кол-во баллов'),
        ),
    ]
