# Generated by Django 3.2.9 on 2022-06-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
        ('courses', '0006_auto_20220607_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('Автоматическая проверка', 'Автоматическая проверка'), ('Ручная проверка', 'Ручная проверка')], default='Автоматическая проверка', max_length=23, verbose_name='Тип чек-поинта')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.RemoveField(
            model_name='multiselectrightansweroptions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='onerightansweroptions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.DeleteModel(
            name='MultiSelectQuestion',
        ),
        migrations.DeleteModel(
            name='MultiSelectRightAnswerOptions',
        ),
        migrations.DeleteModel(
            name='OneRightAnswerOptions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
