# Generated by Django 3.2.9 on 2022-06-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220607_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'verbose_name': 'Чек поинт', 'verbose_name_plural': 'Чек поинты'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/tasks/files/%Y/%m/%d/', verbose_name='Файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Файл задания',
                'verbose_name_plural': 'Файлы задания',
            },
        ),
    ]
