# Generated by Django 3.2.9 on 2022-06-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220607_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
