# Generated by Django 3.2.9 on 2022-06-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_checkpoint_after_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='after_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_task_check_points', to='courses.task', verbose_name='После задания'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_in_check_points', to='courses.task', verbose_name='Задание'),
        ),
    ]
