# Generated by Django 3.2.9 on 2022-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220607_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_last_task',
        ),
        migrations.AddField(
            model_name='task',
            name='is_check_point',
            field=models.BooleanField(null=True, verbose_name='Это задание чек поинт'),
        ),
    ]
