# Generated by Django 3.2.9 on 2022-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220607_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_check_point',
            field=models.BooleanField(default=False, verbose_name='Это задание чек поинт'),
        ),
    ]
