# Generated by Django 3.2.9 on 2022-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_task_is_check_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_check_point',
            field=models.BooleanField(default=False, verbose_name='Это задание чек поинт?'),
        ),
        migrations.DeleteModel(
            name='CheckPoint',
        ),
    ]
