# Generated by Django 3.2.9 on 2022-05-28 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_auto_20220528_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchievementUser',
            new_name='UserAchievement',
        ),
    ]
