# Generated by Django 3.2.9 on 2022-05-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_rename_achievementuser_userachievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userachievement',
            old_name='achivement',
            new_name='achievement',
        ),
    ]
