# Generated by Django 3.2.9 on 2022-06-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_сalendar', '0005_auto_20220418_2136'),
        ('gamification', '0004_rename_achivement_userachievement_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='user_page_images', verbose_name='Фото')),
                ('description', models.CharField(max_length=150, verbose_name='Информация о себе')),
                ('achievements_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.userachievement', verbose_name='Достигнутые достижения')),
                ('event_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_сalendar.event', verbose_name='Календарь событий')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Страница пользователя',
                'verbose_name_plural': 'Страницы пользователей',
            },
        ),
    ]
