# Generated by Django 3.2.9 on 2022-03-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('встреча', 'Встреча'), ('дедлайн задания', 'Дедланй задания')], default='встреча', max_length=15, verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='NotificationMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('send_to_all_users', models.BooleanField(verbose_name='Отправить всем пользователям')),
                ('text', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('встреча', 'Встреча'), ('дедлайн задания', 'Дедланй задания')], default='встреча', max_length=15, verbose_name='Тип')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рассылка уведомления',
                'verbose_name_plural': 'Рассылка уведомления',
            },
        ),
    ]
