# Generated by Django 3.2.9 on 2022-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
