# Generated by Django 3.2.9 on 2022-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media_library.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media_library.Topic', verbose_name='Темы'),
        ),
    ]
